### ISSUE TITLE
search and return the string as model string representation __str

### ISSUE THREAD

**Issue by rajeshr188** [PHACDataHub/django-htmx-autocomplete#32]
i dont understand how the search works but one of the charfield from model is searched when i type in select input,but i want the string represenation of the model to be searched and displayed in options of the select element.is it possible in this library?

for example i have a model

class Customer(models.Model)
name = CharField()
phonenumber = phonenumberfield()

def __str__(self):
return f"{self.name} {self.phonenumber}"    <----------this shall be seached and displayed in select options

**Comment by lucbelliveau** [comment]
By default the search happens on the first text field of the model - this can overridden by changing `item_label`.  

https://github.com/PHACDataHub/django-htmx-autocomplete/blob/main/autocomplete/autocomplete.py#L56

To search using the str representation you can override the `get_items` function.. here is an example of that:

https://github.com/PHACDataHub/django-htmx-autocomplete/blob/main/tests/app/ac_test/forms.py#L59
